### ISSUE TITLE
Speed comparison

### ISSUE THREAD

**Issue by caub** [emn178/js-md5#19]
just did this https://jsfiddle.net/crl/6uaktq3s/ that shows that your lib is the fastest around, and deserve more  credit

**Comment by tnajdek** [comment]
Thanks for sharing the speed comparison demo @caub!

I wasn't convinced by "way slower" so I've [uncommented some code](https://jsfiddle.net/6uaktq3s/9/) to find out that proverb aka [node-md5](https://github.com/pvorb/node-md5) is about 50 times slower (10MB test file, 3-yo MBP).

I believe it could make many developers life easier if this package included a speed comparison table in the README file.

**Comment by AlttiRi** [comment]
Confirm.
It's works 6-7 times faster than plain old [CryptoJS](https://code.google.com/archive/p/crypto-js/downloads), or [md5.js](https://github.com/crypto-browserify/md5.js) ([with over 8kk weekly downloads](https://www.npmjs.com/package/md5.js)).

I think it's due to the using of Uint32Array. But does this code will work on Big-Endian machines?

**Comment by NamelessContributor** [comment]
> will this code work on Big-Endian machines?

I tested it on qemu ppc64 and it produced wrong results as expected.

**Comment by AlttiRi** [comment]
It's was used in a browser (Do they work fine in BE-machines?), or in Node.js?

**Comment by emn178** [comment]
added benchmarks to README
