### ISSUE TITLE
Fix receive integer value

### ISSUE THREAD

**Issue by jorgemarcondes** [emn178/js-md5#5]
Can you fix to receive integer value?
Just add a .toString() at parameter and up to bower?

**Comment by emn178** [comment]
why not do this before call method?

**Comment by jorgemarcondes** [comment]
Because im migrating from another md5 library.

**Comment by atayahmet** [comment]
Hi @emn178 

Please can you fix that integer value problem?

**Comment by emn178** [comment]
Hi,

I'm not sure this is good behavior. Imagine a situation that the user processed something and passed result to md5 function.
```JavaScript
md5(expectToReturnString());
```
And it had a bug and returned a non-string result. He wouldn't know about this. This could be hard to debug.
I think it's better to throw an exception if input is not allowed.
Actually, current version doesn't throw exception and has this problem. So I prefer to change the behavior to raise exception rather than allow everything. Users should handle disallowed types before md5.

How do you think?

**Comment by raphinesse** [comment]
Automatically calling `toString()` could also mask bugs where a custom type is passed in, but its `toString()` is only used for pretty printing purposes. The user might assume everything is fine while not creating representational hashes for her objects. Therefore I would throw an error on any unsupported type.

**Comment by emn178** [comment]
v0.5.0 has changed the behavior. It will throw an error if input is incorrect.
